### ISSUE TITLE
[idea] Proposal to be included in the symfony cli binary

### ISSUE THREAD

**Issue by noniagriconomie** [strangebuzz/sfcw#6]
Hello,

First thank you for this, i will give it a try on one of my project :)

The issue is about proposing this feature inside the symfony/cli tools

Either with a new cli or with an option when running the server for example

I think, it can be a nice addition on this tool, and avoid having 2 packages

Cheers!

**Comment by COil** [comment]
Hello @noniagriconomie , thanks for proposing this idea. The major problem I see currently is that the Symfony CLI isn't open-source.

**Comment by noniagriconomie** [comment]
@COil yes but you can open an issue asking for this idea to be implemented :)
