### ISSUE TITLE
Links to download executable

### ISSUE THREAD

**Issue by MartinRN** [strangebuzz/sfcw#8]
The links to download executable seems to be broken. Is there any chance you could fix it ? Thanks.

**Comment by COil** [comment]
Hello Martin, yes you are right, the dedicated domain has been shutdown. I think I will transfer the links to https://strangebuzz.com before getting another domain. Thanks for reporting the problem, I'll update this issue as soon as done. See you. COil 🙂

**Comment by MartinRN** [comment]
Thanks for the reply! Can't wait to test this.

**Comment by COil** [comment]
Hello, the executables links are back.
